# Generated by Django 5.2.6 on 2025-09-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramUser',
            new_name='TelegramUserModel',
        ),
        migrations.AddField(
            model_name='taskhistorymodel',
            name='field_changed',
            field=models.CharField(default='unknown', max_length=50, verbose_name='Поле'),
            preserve_default=False,
        ),
    ]
