# Generated by Django 5.2.6 on 2025-11-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='task_file/', verbose_name='Файл'),
        ),
    ]
