# Generated by Django 5.2.6 on 2025-11-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remove_taskmodel_file_taskfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfile',
            options={},
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='telegram_id',
        ),
    ]
