# Generated by Django 5.2.8 on 2025-11-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_taskfile_options_remove_usermodel_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='telegram_link_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='telegram_link_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
