# Generated by Django 5.2.8 on 2025-11-24 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_usermodel_telegram_link_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
