# Generated by Django 5.2.8 on 2025-11-27 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_alter_telegramusermodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskHistoryModel',
        ),
    ]
