# Generated by Django 5.2.8 on 2025-11-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username'),
        ),
    ]
